// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: blink_detection.proto

package blink_detection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlinkDetectionService_AnalyzeBlink_FullMethodName  = "/blink_detection.BlinkDetectionService/AnalyzeBlink"
	BlinkDetectionService_StreamAnalyze_FullMethodName = "/blink_detection.BlinkDetectionService/StreamAnalyze"
	BlinkDetectionService_ResetTrack_FullMethodName    = "/blink_detection.BlinkDetectionService/ResetTrack"
	BlinkDetectionService_Health_FullMethodName        = "/blink_detection.BlinkDetectionService/Health"
)

// BlinkDetectionServiceClient is the client API for BlinkDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Blink Detection Microservice
type BlinkDetectionServiceClient interface {
	// Analyze blink from landmarks
	AnalyzeBlink(ctx context.Context, in *BlinkRequest, opts ...grpc.CallOption) (*BlinkResponse, error)
	// Stream analysis with state tracking
	StreamAnalyze(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BlinkRequest, BlinkResponse], error)
	// Reset state for a track
	ResetTrack(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type blinkDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlinkDetectionServiceClient(cc grpc.ClientConnInterface) BlinkDetectionServiceClient {
	return &blinkDetectionServiceClient{cc}
}

func (c *blinkDetectionServiceClient) AnalyzeBlink(ctx context.Context, in *BlinkRequest, opts ...grpc.CallOption) (*BlinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlinkResponse)
	err := c.cc.Invoke(ctx, BlinkDetectionService_AnalyzeBlink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blinkDetectionServiceClient) StreamAnalyze(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BlinkRequest, BlinkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlinkDetectionService_ServiceDesc.Streams[0], BlinkDetectionService_StreamAnalyze_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BlinkRequest, BlinkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlinkDetectionService_StreamAnalyzeClient = grpc.BidiStreamingClient[BlinkRequest, BlinkResponse]

func (c *blinkDetectionServiceClient) ResetTrack(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, BlinkDetectionService_ResetTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blinkDetectionServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BlinkDetectionService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlinkDetectionServiceServer is the server API for BlinkDetectionService service.
// All implementations must embed UnimplementedBlinkDetectionServiceServer
// for forward compatibility.
//
// Blink Detection Microservice
type BlinkDetectionServiceServer interface {
	// Analyze blink from landmarks
	AnalyzeBlink(context.Context, *BlinkRequest) (*BlinkResponse, error)
	// Stream analysis with state tracking
	StreamAnalyze(grpc.BidiStreamingServer[BlinkRequest, BlinkResponse]) error
	// Reset state for a track
	ResetTrack(context.Context, *ResetRequest) (*ResetResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedBlinkDetectionServiceServer()
}

// UnimplementedBlinkDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlinkDetectionServiceServer struct{}

func (UnimplementedBlinkDetectionServiceServer) AnalyzeBlink(context.Context, *BlinkRequest) (*BlinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeBlink not implemented")
}
func (UnimplementedBlinkDetectionServiceServer) StreamAnalyze(grpc.BidiStreamingServer[BlinkRequest, BlinkResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAnalyze not implemented")
}
func (UnimplementedBlinkDetectionServiceServer) ResetTrack(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetTrack not implemented")
}
func (UnimplementedBlinkDetectionServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBlinkDetectionServiceServer) mustEmbedUnimplementedBlinkDetectionServiceServer() {}
func (UnimplementedBlinkDetectionServiceServer) testEmbeddedByValue()                               {}

// UnsafeBlinkDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlinkDetectionServiceServer will
// result in compilation errors.
type UnsafeBlinkDetectionServiceServer interface {
	mustEmbedUnimplementedBlinkDetectionServiceServer()
}

func RegisterBlinkDetectionServiceServer(s grpc.ServiceRegistrar, srv BlinkDetectionServiceServer) {
	// If the following call panics, it indicates UnimplementedBlinkDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlinkDetectionService_ServiceDesc, srv)
}

func _BlinkDetectionService_AnalyzeBlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlinkDetectionServiceServer).AnalyzeBlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlinkDetectionService_AnalyzeBlink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlinkDetectionServiceServer).AnalyzeBlink(ctx, req.(*BlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlinkDetectionService_StreamAnalyze_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlinkDetectionServiceServer).StreamAnalyze(&grpc.GenericServerStream[BlinkRequest, BlinkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlinkDetectionService_StreamAnalyzeServer = grpc.BidiStreamingServer[BlinkRequest, BlinkResponse]

func _BlinkDetectionService_ResetTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlinkDetectionServiceServer).ResetTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlinkDetectionService_ResetTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlinkDetectionServiceServer).ResetTrack(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlinkDetectionService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlinkDetectionServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlinkDetectionService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlinkDetectionServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlinkDetectionService_ServiceDesc is the grpc.ServiceDesc for BlinkDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlinkDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blink_detection.BlinkDetectionService",
	HandlerType: (*BlinkDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeBlink",
			Handler:    _BlinkDetectionService_AnalyzeBlink_Handler,
		},
		{
			MethodName: "ResetTrack",
			Handler:    _BlinkDetectionService_ResetTrack_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BlinkDetectionService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAnalyze",
			Handler:       _BlinkDetectionService_StreamAnalyze_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "blink_detection.proto",
}
