// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: attention.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttentionService_ProcessFrame_FullMethodName = "/attention.AttentionService/ProcessFrame"
	AttentionService_StreamFrames_FullMethodName = "/attention.AttentionService/StreamFrames"
	AttentionService_HealthCheck_FullMethodName  = "/attention.AttentionService/HealthCheck"
)

// AttentionServiceClient is the client API for AttentionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI Processing Service
type AttentionServiceClient interface {
	// Process a single frame and return attention results
	ProcessFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameResponse, error)
	// Stream frames for real-time processing
	StreamFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, FrameResponse], error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type attentionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttentionServiceClient(cc grpc.ClientConnInterface) AttentionServiceClient {
	return &attentionServiceClient{cc}
}

func (c *attentionServiceClient) ProcessFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrameResponse)
	err := c.cc.Invoke(ctx, AttentionService_ProcessFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attentionServiceClient) StreamFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FrameRequest, FrameResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttentionService_ServiceDesc.Streams[0], AttentionService_StreamFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FrameRequest, FrameResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttentionService_StreamFramesClient = grpc.BidiStreamingClient[FrameRequest, FrameResponse]

func (c *attentionServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AttentionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttentionServiceServer is the server API for AttentionService service.
// All implementations must embed UnimplementedAttentionServiceServer
// for forward compatibility.
//
// AI Processing Service
type AttentionServiceServer interface {
	// Process a single frame and return attention results
	ProcessFrame(context.Context, *FrameRequest) (*FrameResponse, error)
	// Stream frames for real-time processing
	StreamFrames(grpc.BidiStreamingServer[FrameRequest, FrameResponse]) error
	// Health check
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAttentionServiceServer()
}

// UnimplementedAttentionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttentionServiceServer struct{}

func (UnimplementedAttentionServiceServer) ProcessFrame(context.Context, *FrameRequest) (*FrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessFrame not implemented")
}
func (UnimplementedAttentionServiceServer) StreamFrames(grpc.BidiStreamingServer[FrameRequest, FrameResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamFrames not implemented")
}
func (UnimplementedAttentionServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAttentionServiceServer) mustEmbedUnimplementedAttentionServiceServer() {}
func (UnimplementedAttentionServiceServer) testEmbeddedByValue()                          {}

// UnsafeAttentionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttentionServiceServer will
// result in compilation errors.
type UnsafeAttentionServiceServer interface {
	mustEmbedUnimplementedAttentionServiceServer()
}

func RegisterAttentionServiceServer(s grpc.ServiceRegistrar, srv AttentionServiceServer) {
	// If the following call panics, it indicates UnimplementedAttentionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttentionService_ServiceDesc, srv)
}

func _AttentionService_ProcessFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttentionServiceServer).ProcessFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttentionService_ProcessFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttentionServiceServer).ProcessFrame(ctx, req.(*FrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttentionService_StreamFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AttentionServiceServer).StreamFrames(&grpc.GenericServerStream[FrameRequest, FrameResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttentionService_StreamFramesServer = grpc.BidiStreamingServer[FrameRequest, FrameResponse]

func _AttentionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttentionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttentionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttentionServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttentionService_ServiceDesc is the grpc.ServiceDesc for AttentionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttentionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attention.AttentionService",
	HandlerType: (*AttentionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessFrame",
			Handler:    _AttentionService_ProcessFrame_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AttentionService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFrames",
			Handler:       _AttentionService_StreamFrames_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "attention.proto",
}
