// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: attention.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame request
type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	FrameData     []byte                 `protobuf:"bytes,3,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"` // JPEG/PNG encoded image
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp in milliseconds
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_attention_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *FrameRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *FrameRequest) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *FrameRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FrameRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Frame response with attention results
type FrameResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MeetingId        string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	ParticipantId    string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Timestamp        int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Faces            []*FaceResult          `protobuf:"bytes,4,rep,name=faces,proto3" json:"faces,omitempty"`
	ProcessingTimeMs float32                `protobuf:"fixed32,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	Success          bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_attention_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{1}
}

func (x *FrameResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *FrameResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *FrameResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FrameResponse) GetFaces() []*FaceResult {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *FrameResponse) GetProcessingTimeMs() float32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *FrameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FrameResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Individual face result
type FaceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       int32                  `protobuf:"varint,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Attention     *AttentionMetrics      `protobuf:"bytes,3,opt,name=attention,proto3" json:"attention,omitempty"`
	HeadPose      *HeadPose              `protobuf:"bytes,4,opt,name=head_pose,json=headPose,proto3" json:"head_pose,omitempty"`
	Gaze          *GazeInfo              `protobuf:"bytes,5,opt,name=gaze,proto3" json:"gaze,omitempty"`
	Eyes          *EyeInfo               `protobuf:"bytes,6,opt,name=eyes,proto3" json:"eyes,omitempty"`
	Alerts        []*Alert               `protobuf:"bytes,7,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceResult) Reset() {
	*x = FaceResult{}
	mi := &file_attention_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceResult) ProtoMessage() {}

func (x *FaceResult) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceResult.ProtoReflect.Descriptor instead.
func (*FaceResult) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{2}
}

func (x *FaceResult) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *FaceResult) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *FaceResult) GetAttention() *AttentionMetrics {
	if x != nil {
		return x.Attention
	}
	return nil
}

func (x *FaceResult) GetHeadPose() *HeadPose {
	if x != nil {
		return x.HeadPose
	}
	return nil
}

func (x *FaceResult) GetGaze() *GazeInfo {
	if x != nil {
		return x.Gaze
	}
	return nil
}

func (x *FaceResult) GetEyes() *EyeInfo {
	if x != nil {
		return x.Eyes
	}
	return nil
}

func (x *FaceResult) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// Bounding box
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_attention_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{3}
}

func (x *BoundingBox) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BoundingBox) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BoundingBox) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BoundingBox) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *BoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Attention metrics
type AttentionMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AttentionScore   float32                `protobuf:"fixed32,1,opt,name=attention_score,json=attentionScore,proto3" json:"attention_score,omitempty"`         // 0-100
	GazeScore        float32                `protobuf:"fixed32,2,opt,name=gaze_score,json=gazeScore,proto3" json:"gaze_score,omitempty"`                        // 0-1
	HeadPoseScore    float32                `protobuf:"fixed32,3,opt,name=head_pose_score,json=headPoseScore,proto3" json:"head_pose_score,omitempty"`          // 0-1
	EyeOpennessScore float32                `protobuf:"fixed32,4,opt,name=eye_openness_score,json=eyeOpennessScore,proto3" json:"eye_openness_score,omitempty"` // 0-1
	PresenceScore    float32                `protobuf:"fixed32,5,opt,name=presence_score,json=presenceScore,proto3" json:"presence_score,omitempty"`            // 0-1
	AttentionLevel   string                 `protobuf:"bytes,6,opt,name=attention_level,json=attentionLevel,proto3" json:"attention_level,omitempty"`           // high/medium/low/very_low
	IsAttentive      bool                   `protobuf:"varint,7,opt,name=is_attentive,json=isAttentive,proto3" json:"is_attentive,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttentionMetrics) Reset() {
	*x = AttentionMetrics{}
	mi := &file_attention_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttentionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttentionMetrics) ProtoMessage() {}

func (x *AttentionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttentionMetrics.ProtoReflect.Descriptor instead.
func (*AttentionMetrics) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{4}
}

func (x *AttentionMetrics) GetAttentionScore() float32 {
	if x != nil {
		return x.AttentionScore
	}
	return 0
}

func (x *AttentionMetrics) GetGazeScore() float32 {
	if x != nil {
		return x.GazeScore
	}
	return 0
}

func (x *AttentionMetrics) GetHeadPoseScore() float32 {
	if x != nil {
		return x.HeadPoseScore
	}
	return 0
}

func (x *AttentionMetrics) GetEyeOpennessScore() float32 {
	if x != nil {
		return x.EyeOpennessScore
	}
	return 0
}

func (x *AttentionMetrics) GetPresenceScore() float32 {
	if x != nil {
		return x.PresenceScore
	}
	return 0
}

func (x *AttentionMetrics) GetAttentionLevel() string {
	if x != nil {
		return x.AttentionLevel
	}
	return ""
}

func (x *AttentionMetrics) GetIsAttentive() bool {
	if x != nil {
		return x.IsAttentive
	}
	return false
}

// Head pose
type HeadPose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yaw           float32                `protobuf:"fixed32,1,opt,name=yaw,proto3" json:"yaw,omitempty"` // degrees
	Pitch         float32                `protobuf:"fixed32,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Roll          float32                `protobuf:"fixed32,3,opt,name=roll,proto3" json:"roll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadPose) Reset() {
	*x = HeadPose{}
	mi := &file_attention_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadPose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadPose) ProtoMessage() {}

func (x *HeadPose) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadPose.ProtoReflect.Descriptor instead.
func (*HeadPose) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{5}
}

func (x *HeadPose) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *HeadPose) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *HeadPose) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

// Gaze information
type GazeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GazeX             float32                `protobuf:"fixed32,1,opt,name=gaze_x,json=gazeX,proto3" json:"gaze_x,omitempty"` // normalized -1 to 1
	GazeY             float32                `protobuf:"fixed32,2,opt,name=gaze_y,json=gazeY,proto3" json:"gaze_y,omitempty"`
	IsLookingAtCamera bool                   `protobuf:"varint,3,opt,name=is_looking_at_camera,json=isLookingAtCamera,proto3" json:"is_looking_at_camera,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GazeInfo) Reset() {
	*x = GazeInfo{}
	mi := &file_attention_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GazeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GazeInfo) ProtoMessage() {}

func (x *GazeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GazeInfo.ProtoReflect.Descriptor instead.
func (*GazeInfo) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{6}
}

func (x *GazeInfo) GetGazeX() float32 {
	if x != nil {
		return x.GazeX
	}
	return 0
}

func (x *GazeInfo) GetGazeY() float32 {
	if x != nil {
		return x.GazeY
	}
	return 0
}

func (x *GazeInfo) GetIsLookingAtCamera() bool {
	if x != nil {
		return x.IsLookingAtCamera
	}
	return false
}

// Eye information
type EyeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftEar       float32                `protobuf:"fixed32,1,opt,name=left_ear,json=leftEar,proto3" json:"left_ear,omitempty"` // Eye Aspect Ratio
	RightEar      float32                `protobuf:"fixed32,2,opt,name=right_ear,json=rightEar,proto3" json:"right_ear,omitempty"`
	AvgEar        float32                `protobuf:"fixed32,3,opt,name=avg_ear,json=avgEar,proto3" json:"avg_ear,omitempty"`
	Perclos       float32                `protobuf:"fixed32,4,opt,name=perclos,proto3" json:"perclos,omitempty"` // Percent of eye closure
	IsBlinking    bool                   `protobuf:"varint,5,opt,name=is_blinking,json=isBlinking,proto3" json:"is_blinking,omitempty"`
	IsDrowsy      bool                   `protobuf:"varint,6,opt,name=is_drowsy,json=isDrowsy,proto3" json:"is_drowsy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EyeInfo) Reset() {
	*x = EyeInfo{}
	mi := &file_attention_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EyeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EyeInfo) ProtoMessage() {}

func (x *EyeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EyeInfo.ProtoReflect.Descriptor instead.
func (*EyeInfo) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{7}
}

func (x *EyeInfo) GetLeftEar() float32 {
	if x != nil {
		return x.LeftEar
	}
	return 0
}

func (x *EyeInfo) GetRightEar() float32 {
	if x != nil {
		return x.RightEar
	}
	return 0
}

func (x *EyeInfo) GetAvgEar() float32 {
	if x != nil {
		return x.AvgEar
	}
	return 0
}

func (x *EyeInfo) GetPerclos() float32 {
	if x != nil {
		return x.Perclos
	}
	return 0
}

func (x *EyeInfo) GetIsBlinking() bool {
	if x != nil {
		return x.IsBlinking
	}
	return false
}

func (x *EyeInfo) GetIsDrowsy() bool {
	if x != nil {
		return x.IsDrowsy
	}
	return false
}

// Alert
type Alert struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AlertType       string                 `protobuf:"bytes,1,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"` // not_attentive, looking_away, drowsy
	Severity        string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`                    // info, warning, critical
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DurationSeconds float32                `protobuf:"fixed32,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_attention_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{8}
}

func (x *Alert) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// Health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_attention_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Healthy         bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Device          string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"` // cpu/cuda
	GpuMemoryUsedMb float32                `protobuf:"fixed32,4,opt,name=gpu_memory_used_mb,json=gpuMemoryUsedMb,proto3" json:"gpu_memory_used_mb,omitempty"`
	ActiveSessions  int32                  `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_attention_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attention_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_attention_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HealthResponse) GetGpuMemoryUsedMb() float32 {
	if x != nil {
		return x.GpuMemoryUsedMb
	}
	return 0
}

func (x *HealthResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

var File_attention_proto protoreflect.FileDescriptor

const file_attention_proto_rawDesc = "" +
	"\n" +
	"\x0fattention.proto\x12\tattention\"\xbf\x01\n" +
	"\fFrameRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x03 \x01(\fR\tframeData\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\"\x8d\x02\n" +
	"\rFrameResponse\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12+\n" +
	"\x05faces\x18\x04 \x03(\v2\x15.attention.FaceResultR\x05faces\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x02R\x10processingTimeMs\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\xbb\x02\n" +
	"\n" +
	"FaceResult\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\x05R\atrackId\x12*\n" +
	"\x04bbox\x18\x02 \x01(\v2\x16.attention.BoundingBoxR\x04bbox\x129\n" +
	"\tattention\x18\x03 \x01(\v2\x1b.attention.AttentionMetricsR\tattention\x120\n" +
	"\thead_pose\x18\x04 \x01(\v2\x13.attention.HeadPoseR\bheadPose\x12'\n" +
	"\x04gaze\x18\x05 \x01(\v2\x13.attention.GazeInfoR\x04gaze\x12&\n" +
	"\x04eyes\x18\x06 \x01(\v2\x12.attention.EyeInfoR\x04eyes\x12(\n" +
	"\x06alerts\x18\a \x03(\v2\x10.attention.AlertR\x06alerts\"m\n" +
	"\vBoundingBox\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x02R\x02y2\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\"\xa3\x02\n" +
	"\x10AttentionMetrics\x12'\n" +
	"\x0fattention_score\x18\x01 \x01(\x02R\x0eattentionScore\x12\x1d\n" +
	"\n" +
	"gaze_score\x18\x02 \x01(\x02R\tgazeScore\x12&\n" +
	"\x0fhead_pose_score\x18\x03 \x01(\x02R\rheadPoseScore\x12,\n" +
	"\x12eye_openness_score\x18\x04 \x01(\x02R\x10eyeOpennessScore\x12%\n" +
	"\x0epresence_score\x18\x05 \x01(\x02R\rpresenceScore\x12'\n" +
	"\x0fattention_level\x18\x06 \x01(\tR\x0eattentionLevel\x12!\n" +
	"\fis_attentive\x18\a \x01(\bR\visAttentive\"F\n" +
	"\bHeadPose\x12\x10\n" +
	"\x03yaw\x18\x01 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x02 \x01(\x02R\x05pitch\x12\x12\n" +
	"\x04roll\x18\x03 \x01(\x02R\x04roll\"i\n" +
	"\bGazeInfo\x12\x15\n" +
	"\x06gaze_x\x18\x01 \x01(\x02R\x05gazeX\x12\x15\n" +
	"\x06gaze_y\x18\x02 \x01(\x02R\x05gazeY\x12/\n" +
	"\x14is_looking_at_camera\x18\x03 \x01(\bR\x11isLookingAtCamera\"\xb2\x01\n" +
	"\aEyeInfo\x12\x19\n" +
	"\bleft_ear\x18\x01 \x01(\x02R\aleftEar\x12\x1b\n" +
	"\tright_ear\x18\x02 \x01(\x02R\brightEar\x12\x17\n" +
	"\aavg_ear\x18\x03 \x01(\x02R\x06avgEar\x12\x18\n" +
	"\aperclos\x18\x04 \x01(\x02R\aperclos\x12\x1f\n" +
	"\vis_blinking\x18\x05 \x01(\bR\n" +
	"isBlinking\x12\x1b\n" +
	"\tis_drowsy\x18\x06 \x01(\bR\bisDrowsy\"\x87\x01\n" +
	"\x05Alert\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x01 \x01(\tR\talertType\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x02R\x0fdurationSeconds\"\x0f\n" +
	"\rHealthRequest\"\xb2\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12+\n" +
	"\x12gpu_memory_used_mb\x18\x04 \x01(\x02R\x0fgpuMemoryUsedMb\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\x05R\x0eactiveSessions2\xe0\x01\n" +
	"\x10AttentionService\x12A\n" +
	"\fProcessFrame\x12\x17.attention.FrameRequest\x1a\x18.attention.FrameResponse\x12E\n" +
	"\fStreamFrames\x12\x17.attention.FrameRequest\x1a\x18.attention.FrameResponse(\x010\x01\x12B\n" +
	"\vHealthCheck\x12\x18.attention.HealthRequest\x1a\x19.attention.HealthResponseB6Z4github.com/attention-detection/api-gateway/pkg/protob\x06proto3"

var (
	file_attention_proto_rawDescOnce sync.Once
	file_attention_proto_rawDescData []byte
)

func file_attention_proto_rawDescGZIP() []byte {
	file_attention_proto_rawDescOnce.Do(func() {
		file_attention_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attention_proto_rawDesc), len(file_attention_proto_rawDesc)))
	})
	return file_attention_proto_rawDescData
}

var file_attention_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_attention_proto_goTypes = []any{
	(*FrameRequest)(nil),     // 0: attention.FrameRequest
	(*FrameResponse)(nil),    // 1: attention.FrameResponse
	(*FaceResult)(nil),       // 2: attention.FaceResult
	(*BoundingBox)(nil),      // 3: attention.BoundingBox
	(*AttentionMetrics)(nil), // 4: attention.AttentionMetrics
	(*HeadPose)(nil),         // 5: attention.HeadPose
	(*GazeInfo)(nil),         // 6: attention.GazeInfo
	(*EyeInfo)(nil),          // 7: attention.EyeInfo
	(*Alert)(nil),            // 8: attention.Alert
	(*HealthRequest)(nil),    // 9: attention.HealthRequest
	(*HealthResponse)(nil),   // 10: attention.HealthResponse
}
var file_attention_proto_depIdxs = []int32{
	2,  // 0: attention.FrameResponse.faces:type_name -> attention.FaceResult
	3,  // 1: attention.FaceResult.bbox:type_name -> attention.BoundingBox
	4,  // 2: attention.FaceResult.attention:type_name -> attention.AttentionMetrics
	5,  // 3: attention.FaceResult.head_pose:type_name -> attention.HeadPose
	6,  // 4: attention.FaceResult.gaze:type_name -> attention.GazeInfo
	7,  // 5: attention.FaceResult.eyes:type_name -> attention.EyeInfo
	8,  // 6: attention.FaceResult.alerts:type_name -> attention.Alert
	0,  // 7: attention.AttentionService.ProcessFrame:input_type -> attention.FrameRequest
	0,  // 8: attention.AttentionService.StreamFrames:input_type -> attention.FrameRequest
	9,  // 9: attention.AttentionService.HealthCheck:input_type -> attention.HealthRequest
	1,  // 10: attention.AttentionService.ProcessFrame:output_type -> attention.FrameResponse
	1,  // 11: attention.AttentionService.StreamFrames:output_type -> attention.FrameResponse
	10, // 12: attention.AttentionService.HealthCheck:output_type -> attention.HealthResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_attention_proto_init() }
func file_attention_proto_init() {
	if File_attention_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attention_proto_rawDesc), len(file_attention_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attention_proto_goTypes,
		DependencyIndexes: file_attention_proto_depIdxs,
		MessageInfos:      file_attention_proto_msgTypes,
	}.Build()
	File_attention_proto = out.File
	file_attention_proto_goTypes = nil
	file_attention_proto_depIdxs = nil
}
