// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: gaze_tracking.proto

package gaze_tracking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GazeTrackingService_EstimateGaze_FullMethodName  = "/gaze_tracking.GazeTrackingService/EstimateGaze"
	GazeTrackingService_BatchEstimate_FullMethodName = "/gaze_tracking.GazeTrackingService/BatchEstimate"
	GazeTrackingService_Health_FullMethodName        = "/gaze_tracking.GazeTrackingService/Health"
)

// GazeTrackingServiceClient is the client API for GazeTrackingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gaze Tracking Microservice
type GazeTrackingServiceClient interface {
	// Estimate gaze direction from landmarks
	EstimateGaze(ctx context.Context, in *GazeRequest, opts ...grpc.CallOption) (*GazeResponse, error)
	// Batch estimation
	BatchEstimate(ctx context.Context, in *BatchGazeRequest, opts ...grpc.CallOption) (*BatchGazeResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type gazeTrackingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGazeTrackingServiceClient(cc grpc.ClientConnInterface) GazeTrackingServiceClient {
	return &gazeTrackingServiceClient{cc}
}

func (c *gazeTrackingServiceClient) EstimateGaze(ctx context.Context, in *GazeRequest, opts ...grpc.CallOption) (*GazeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GazeResponse)
	err := c.cc.Invoke(ctx, GazeTrackingService_EstimateGaze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gazeTrackingServiceClient) BatchEstimate(ctx context.Context, in *BatchGazeRequest, opts ...grpc.CallOption) (*BatchGazeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGazeResponse)
	err := c.cc.Invoke(ctx, GazeTrackingService_BatchEstimate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gazeTrackingServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GazeTrackingService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GazeTrackingServiceServer is the server API for GazeTrackingService service.
// All implementations must embed UnimplementedGazeTrackingServiceServer
// for forward compatibility.
//
// Gaze Tracking Microservice
type GazeTrackingServiceServer interface {
	// Estimate gaze direction from landmarks
	EstimateGaze(context.Context, *GazeRequest) (*GazeResponse, error)
	// Batch estimation
	BatchEstimate(context.Context, *BatchGazeRequest) (*BatchGazeResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedGazeTrackingServiceServer()
}

// UnimplementedGazeTrackingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGazeTrackingServiceServer struct{}

func (UnimplementedGazeTrackingServiceServer) EstimateGaze(context.Context, *GazeRequest) (*GazeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateGaze not implemented")
}
func (UnimplementedGazeTrackingServiceServer) BatchEstimate(context.Context, *BatchGazeRequest) (*BatchGazeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchEstimate not implemented")
}
func (UnimplementedGazeTrackingServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGazeTrackingServiceServer) mustEmbedUnimplementedGazeTrackingServiceServer() {}
func (UnimplementedGazeTrackingServiceServer) testEmbeddedByValue()                             {}

// UnsafeGazeTrackingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GazeTrackingServiceServer will
// result in compilation errors.
type UnsafeGazeTrackingServiceServer interface {
	mustEmbedUnimplementedGazeTrackingServiceServer()
}

func RegisterGazeTrackingServiceServer(s grpc.ServiceRegistrar, srv GazeTrackingServiceServer) {
	// If the following call panics, it indicates UnimplementedGazeTrackingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GazeTrackingService_ServiceDesc, srv)
}

func _GazeTrackingService_EstimateGaze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GazeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GazeTrackingServiceServer).EstimateGaze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GazeTrackingService_EstimateGaze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GazeTrackingServiceServer).EstimateGaze(ctx, req.(*GazeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GazeTrackingService_BatchEstimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGazeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GazeTrackingServiceServer).BatchEstimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GazeTrackingService_BatchEstimate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GazeTrackingServiceServer).BatchEstimate(ctx, req.(*BatchGazeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GazeTrackingService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GazeTrackingServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GazeTrackingService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GazeTrackingServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GazeTrackingService_ServiceDesc is the grpc.ServiceDesc for GazeTrackingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GazeTrackingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaze_tracking.GazeTrackingService",
	HandlerType: (*GazeTrackingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstimateGaze",
			Handler:    _GazeTrackingService_EstimateGaze_Handler,
		},
		{
			MethodName: "BatchEstimate",
			Handler:    _GazeTrackingService_BatchEstimate_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _GazeTrackingService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaze_tracking.proto",
}
